name: Playwright Tests

on:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./playwright

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
